///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/Disassembler.aks
/// Generation time: mar oct 30 17:53:30 CET 2018
///

/// Song 'song_ingame' metadata macros
#define song_ingame_address  0x0040
#define song_ingame_size     256
#define song_ingame_end      0x13f

/// Song 'song_ingame' array declaration
extern void song_ingame[song_ingame_size];
